/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.*;

public class GenerateTest extends java.awt.Frame {

    /**
     * Creates new form GenerateTest
     */
    public GenerateTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        

        btnGenerate = new java.awt.Button();
        lblNumberOfQuest = new java.awt.Label();
        txtNumberOfQuest = new java.awt.TextField();
        txtQuestions = new java.awt.TextArea();
        btnBack = new java.awt.Button();


        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        setLayout(new FlowLayout());
        setSize(1000,1000);

        btnGenerate.setLabel("Generate Test");
        add(btnGenerate);
        btnGenerate.setBounds(350, 80, 100, 30);
        btnGenerate.addActionListener(new ButtonClickListener());
        
        btnBack.setLabel("back");
        btnBack.setActionCommand("back");
        btnBack.setBounds(60,400,60,30);
        add(btnBack);
        btnBack.addActionListener(new ButtonClickListener());


        lblNumberOfQuest.setText("No. of Questions");
        add(lblNumberOfQuest);
        lblNumberOfQuest.setBounds(50, 80, 100, 30);

        txtNumberOfQuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfQuestActionPerformed(evt);
            }
        });

        add(txtNumberOfQuest);
        txtNumberOfQuest.setBounds(200, 80, 100, 30);
        add(txtQuestions);
        txtQuestions.setBounds(30, 180, 310, 200);


      
       setLayout(null);



        
    }// </editor-fold>                        

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {                          
        System.exit(0);
    }                         

    private void txtNumberOfQuestActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateTest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify                     
    private java.awt.Button btnGenerate;
    private java.awt.Label lblNumberOfQuest;
    private java.awt.TextField txtNumberOfQuest;
    private java.awt.TextArea txtQuestions;
    private java.awt.Button btnBack;
    String filenameQuest ;
    String filenameAns ;
    String fileNameQuestGen;
    String fileNameAnsGen;
    // End of variables declaration  

    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            if(command.equals("back")){
                btnBack.getParent().setVisible(false);
                new PhysicsHomePage().setVisible(true);
               
            }
            else{
                 if(Subject.Subject.equals("phy")){
                    filenameQuest = ("PhysicsQuestions.txt");
                    filenameAns = ("PhysicsAnswers.txt");
                }
                if(Subject.Subject.equals("chem")){
                    filenameQuest = ("ChemistryQuestions.txt");
                    filenameAns = ("ChemAnswers.txt");
                }
                try{
                    String strQuestforArray;
                    String strAnsforArray;
                    String newQuestion;
                    String newAnswer;
                    int i = 0;
                    FileReader fileReaderQuest = new FileReader(filenameQuest);
                    BufferedReader bufferedReaderQuest = new BufferedReader(fileReaderQuest);
                    FileReader fileReaderAns = new FileReader(filenameAns);
                    BufferedReader bufferedReaderAns = new BufferedReader(fileReaderAns);
                    ArrayList<String> StringOfQuestions = new ArrayList<String>();
                    ArrayList<String> StringOfAnswers = new ArrayList<String>();
                    ArrayList<String> listAllQuestion = new ArrayList<String>();
                    ArrayList<String> listAllAnswer = new ArrayList<String>();
                    ArrayList<String> listGeneratedQuestions = new ArrayList<String>();
                    ArrayList<String> listIndex = new ArrayList<String>();
                    while((strQuestforArray = bufferedReaderQuest.readLine())!=null){
                        StringOfQuestions.add(strQuestforArray);
                        //System.out.println(strQuestforArray);
                    }
                    while((strAnsforArray=bufferedReaderAns.readLine())!=null){
                        StringOfAnswers.add(strAnsforArray);
                        //System.out.println(strAnsforArray);
                    }
                    
                    
                    fileNameQuestGen = ("QuestionGenerated.txt");
                    fileNameAnsGen = ("AnswersGenerated.txt");
                    
                    

                    FileWriter fileWriterQuestGen = new FileWriter(fileNameQuestGen,false);
                    BufferedWriter bufferedWriterQuestGen = new BufferedWriter(fileWriterQuestGen);
                    FileWriter fileWriterAnsGen = new FileWriter(fileNameAnsGen,false);
                    BufferedWriter bufferedWriterAnsGen = new BufferedWriter(fileWriterAnsGen);

                    for(String strQuest : StringOfQuestions){
                        String[] parts = strQuest.split("\\.",2);
                        newQuestion = parts[1];
                        int lastQuestionNumber = Integer.parseInt(parts[0]);
                        while(i!=lastQuestionNumber){
                        listAllQuestion.add(i,newQuestion);
                        listIndex.add(i,parts[0]);
                        //System.out.println(newQuestion);
                        i++;
                    }
                    }
                    i=0;
                    
                    for(String strAns : StringOfAnswers){
                        String[] parts = strAns.split("\\.",2);
                        newAnswer = parts[1];
                        int lastQuestionNumber = Integer.parseInt(parts[0]);
                        while(i!=lastQuestionNumber){
                        listAllAnswer.add(i,newAnswer);
                        //System.out.println(newQuestion);
                        i++;
                    }
                    }

                    //Collections.shuffle(listAllQuestion);
                    Collections.shuffle(listIndex);
                    int j = 0;
                    int numOfQuestions = Integer.parseInt(txtNumberOfQuest.getText().toString());
                    while(j!=numOfQuestions){
                        String strshuffledIndex = listIndex.get(j);
                        int intShuffledIndex = Integer.parseInt(strshuffledIndex);
                        System.out.println(listAllQuestion.get(intShuffledIndex-1));
                        txtQuestions.append(listAllQuestion.get(intShuffledIndex-1) + "\n");
                        bufferedWriterQuestGen.write(listAllQuestion.get(intShuffledIndex-1));
                        bufferedWriterQuestGen.newLine();
                        bufferedWriterQuestGen.flush();
                        /*System.out.println(listAllQuestion.get(j));
                        txtQuestions.append(listAllQuestion.get(j) + "\n");
                        bufferedWriterQuestGen.write(listAllQuestion.get(j));*/
                        //bufferedWriterQuestGen.newLine();
                        //bufferedWriterQuestGen.flush();

                        j++;
                    }
                    j = 0;
                    int numOfAnswers = Integer.parseInt(txtNumberOfQuest.getText().toString());
                    while(j!=numOfAnswers){
                        String strshuffledIndex = listIndex.get(j);
                        int intShuffledIndex = Integer.parseInt(strshuffledIndex);
                        System.out.println(listAllAnswer.get(intShuffledIndex-1));
                        //txtQuestions.append(listAllAnswer.get(intShuffledIndex-1) + "\n");
                        bufferedWriterAnsGen.write(listAllAnswer.get(intShuffledIndex-1));
                        bufferedWriterAnsGen.newLine();
                        bufferedWriterAnsGen.flush();
                        /*System.out.println(listAllQuestion.get(j));
                        txtQuestions.append(listAllQuestion.get(j) + "\n");
                        bufferedWriterQuestGen.write(listAllQuestion.get(j));*/
                        //bufferedWriterQuestGen.newLine();
                        //bufferedWriterQuestGen.flush();

                        j++;
                    }

                    bufferedWriterQuestGen.close();
                    
                }
                catch(IndexOutOfBoundsException iobe){
                    System.out.println("Question list is empty");
                }
                catch(NumberFormatException nfe){
                    System.out.println("number format exception");
                }
                catch(IOException ioe){
                    System.out.println("IO Exception");
                }

            }
        }
    }                 
}