/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */

import java.awt.*;
import java.awt.event.*;
import java.io.*;
public class PhysicsInsertFillInTheBlank extends java.awt.Frame {

    /**
     * Creates new form InsertPhyFillInTheBlank
     */
    public PhysicsInsertFillInTheBlank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new java.awt.Label();
        lblAnswer = new java.awt.Label();
        txtQuestion = new java.awt.TextField();
        txtAnswer = new java.awt.TextField();
        lblDisplay = new java.awt.Label();
        btnInsert = new java.awt.Button();
        btnBack = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setLayout(new FlowLayout());
        setSize(1000,1000);

        lblQuestion.setText("Question");
        add(lblQuestion);
        lblQuestion.setBounds(50, 71, 54, 20);

        lblAnswer.setText("Answer");
        add(lblAnswer);
        lblAnswer.setBounds(50, 127, 45, 20);

        add(txtQuestion);
        txtQuestion.setBounds(130, 71, 145, 20);
        add(txtAnswer);
        txtAnswer.setBounds(130, 127, 145, 20);

        lblDisplay.setText("Insert Fill in the Blank Question");
        add(lblDisplay);
        lblDisplay.setBounds(88, 45, 174, 20);

        btnInsert.setLabel("Insert");
        btnInsert.setActionCommand("insert");
        add(btnInsert);
        btnInsert.setBounds(104, 204, 47, 24);
        btnInsert.addActionListener(new ButtonClickListener());

        btnBack.setLabel("back");
        add(btnBack);
        btnBack.setBounds(302, 248, 42, 24);
        btnBack.addActionListener(new ButtonClickListener());
        btnBack.setActionCommand("back");

        

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsInsertFillInTheBlank().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnInsert;
    private java.awt.Button btnBack;
    private java.awt.Label lblAnswer;
    private java.awt.Label lblDisplay;
    private java.awt.Label lblQuestion;
    private java.awt.TextField txtAnswer;
    private java.awt.TextField txtQuestion;
    String filenameQuest;
    String filenameAns ;
    // End of variables declaration//GEN-END:variables

    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            if(command.equals("back")){
                btnBack.getParent().setVisible(false);
                new PhysicsInsertQuestion().setVisible(true);
            }
            else{
                if(Subject.Subject.equals("phy")){
                    filenameQuest = ("PhysicsQuestions.txt");
                    filenameAns = ("PhysicsAnswers.txt");
                }
                if(Subject.Subject.equals("chem")){
                    filenameQuest = ("ChemistryQuestions.txt");
                    filenameAns = ("ChemAnswers.txt");
                }
                try{
                    FileReader fileReaderQuest = new FileReader(filenameQuest);
                    BufferedReader bufferedReaderQuest = new BufferedReader(fileReaderQuest);
                    FileWriter fileWriterQuest = new FileWriter(filenameQuest,true);
                    BufferedWriter bufferedWriterQuest = new BufferedWriter(fileWriterQuest);
                    int questionNumber = 1;
                    String lineQuest;
                    while((lineQuest = bufferedReaderQuest.readLine()) !=null){
                        questionNumber++;
                    }
                    //bufferedWriter.write(questionNumber + "." +);
                    bufferedWriterQuest.write((questionNumber) + "." + txtQuestion.getText().toString()+ " -Fill in the blank");
                    bufferedWriterQuest.newLine();
                    bufferedWriterQuest.close();

                    //Inserting answer into File
                    FileReader fileReaderAns = new FileReader(filenameAns);
                    BufferedReader bufferedReaderAns= new BufferedReader(fileReaderAns);
                    FileWriter fileWriterAns = new FileWriter(filenameAns,true);
                    BufferedWriter bufferedWriterAns = new BufferedWriter(fileWriterAns);
                    int answerNumber = 1;
                    String lineAns;
                    while((lineAns = bufferedReaderAns.readLine()) !=null){
                        answerNumber++;
                    }
                    //bufferedWriter.write(questionNumber + "." +);
                    bufferedWriterAns.write((answerNumber) + "." + txtAnswer.getText().toString());
                    bufferedWriterAns.newLine();
                    bufferedWriterAns.close();






                }
                catch(IOException ex){
                    System.out.println("error");
                }
            }

        }
    }
}
