/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
public class PhysicsInsertQuestion extends java.awt.Frame {

    /**
     * Creates new form InsertPhysicsQuestion
     */
    public PhysicsInsertQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkgrpQuestionType = new java.awt.CheckboxGroup();
        btngrpQuestionType = new javax.swing.ButtonGroup();
        chkMcq = new javax.swing.JRadioButton();
        chkFill = new javax.swing.JRadioButton();
        chkTrueFalse = new javax.swing.JRadioButton();
        btnBack = new java.awt.Button();
        lblDisplay = new java.awt.Label();
        btnNext = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setLayout(new FlowLayout());
        setSize(1000,1000);

        btngrpQuestionType.add(chkMcq);
        btngrpQuestionType.add(chkTrueFalse);
        btngrpQuestionType.add(chkFill);
        chkMcq.setText("MCQ");
        add(chkMcq);
        chkMcq.setBounds(41, 77, 55, 25);

        chkFill.setText("Fill in the Blank");
        add(chkFill);
         chkFill.setBounds(41, 129, 115, 25);

        chkTrueFalse.setText("True or False");
        chkTrueFalse.setBounds(41, 186, 105, 25);
        add(chkTrueFalse);

        btnBack.setLabel("Back");
        btnBack.setActionCommand("back");
        btnBack.addActionListener(new ButtonClickListener());
        add(btnBack);
        btnBack.setBounds(272, 257, 43, 24);

        
        

        if(Subject.Subject.equals("phy")){
        lblDisplay.setText("Insert Physics Question");
        }
        if(Subject.Subject.equals("chem")){
            lblDisplay.setText("Insert Chemistry Question");
        }
            
        btnNext.setLabel("Next");
        btnNext.setActionCommand("next");
        add(btnNext);
        btnNext.setBounds(114, 257, 40, 24);
        btnNext.addActionListener(new ButtonClickListener());


        

       setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsInsertQuestion().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private javax.swing.JRadioButton chkFill;
    private javax.swing.JRadioButton chkMcq;
    private java.awt.Button btnNext;
    private javax.swing.JRadioButton chkTrueFalse;
    private javax.swing.ButtonGroup btngrpQuestionType;
    private java.awt.Label lblDisplay;
    private java.awt.CheckboxGroup chkgrpQuestionType;
    // End of variables declaration//GEN-END:variables

    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            if(command.equals("back")){
                btnBack.getParent().setVisible(false);
                new PhysicsHomePage().setVisible(true);
            }
            else if(chkMcq.isSelected()){
               chkMcq.getParent().setVisible(false);
               new PhysicsInsertMcqQuest().setVisible(true); 
            }
            else if(chkFill.isSelected()){
                chkFill.getParent().setVisible(false);
                new PhysicsInsertFillInTheBlank().setVisible(true);
            }
            else if(chkTrueFalse.isSelected()){
                chkTrueFalse.getParent().setVisible(false);
                new PhysicsInsertTrueFalseQuest().setVisible(true);
            }
        }
    }
}
