/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.*;

public class PhysicsModifyMcqQuest extends java.awt.Frame {

    /**
     * Creates new form InsertPhyMcqQuest
     */
    int questionNumber;
    public PhysicsModifyMcqQuest(int questionNumberToBeModified) {
        questionNumber = questionNumberToBeModified;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new java.awt.Label();
        lblAnswer = new java.awt.Label();
        lblOptionA = new java.awt.Label();
        lblOptionB = new java.awt.Label();
        lblOptionC = new java.awt.Label();
        lblOptionD = new java.awt.Label();
        lblActionDisplay = new java.awt.Label();
        txtQuestion = new java.awt.TextField();
        txtAnswer = new java.awt.TextField();
        txtOptionA = new java.awt.TextField();
        txtOptionB = new java.awt.TextField();
        txtOptionC = new java.awt.TextField();
        txtOptionD = new java.awt.TextField();
        btnModify = new java.awt.Button();
        btnBack = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setLayout(new FlowLayout());
        setSize(1000,1000);

        lblQuestion.setText("Question");
        add(lblQuestion);
        lblQuestion.setBounds(30, 70, 54, 20);

        lblAnswer.setText("Answer");
        add(lblAnswer);
        lblAnswer.setBounds(30, 116, 45, 20);

        lblOptionA.setText("Option A");
        add(lblOptionA);
        lblOptionA.setBounds(10, 191, 50, 20);

        lblOptionB.setText("Option B");
        add(lblOptionB);
        lblOptionB.setBounds(88, 191, 51, 20);

        lblOptionC.setText("Option C");
         add(lblOptionC);
        lblOptionC.setBounds(164, 191, 52, 20);

        lblOptionD.setText("Option D");
         add(lblOptionD);
        lblOptionD.setBounds(240, 191, 52, 20);

        lblActionDisplay.setText("Modify Question");
        add(lblActionDisplay);
        lblActionDisplay.setBounds(122, 50, 91, 20);

        add(txtQuestion);
        txtQuestion.setBounds(114, 70, 100, 20);
        add(txtAnswer);
        txtAnswer.setBounds(114, 116, 100, 20);
        add(txtOptionA);
        txtOptionA.setBounds(10, 221, 50, 20);
        add(txtOptionB);
        txtOptionB.setBounds(88, 221, 51, 20);
        add(txtOptionC);
        txtOptionC.setBounds(164, 221, 52, 20);
        add(txtOptionD);
        txtOptionD.setBounds(240, 221, 52, 20);

        btnModify.setLabel("Modify Question");
        btnModify.setActionCommand("modify");
        add(btnModify);
        btnModify.setBounds(98, 251, 103, 24);
        btnModify.addActionListener(new ButtonClickListener());

        btnBack.setLabel("Back");
        add(btnBack);
        btnBack.setBounds(319, 266, 43, 24);
        btnBack.setActionCommand("back");
        btnBack.addActionListener(new ButtonClickListener());

        

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsInsertMcqQuest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private java.awt.Button btnModify;
    private java.awt.Label lblActionDisplay;
    private java.awt.Label lblAnswer;
    private java.awt.Label lblOptionA;
    private java.awt.Label lblOptionB;
    private java.awt.Label lblOptionC;
    private java.awt.Label lblOptionD;
    private java.awt.Label lblQuestion;
    private java.awt.TextField txtAnswer;
    private java.awt.TextField txtQuestion;
    private java.awt.TextField txtOptionA;
    private java.awt.TextField txtOptionB;
    private java.awt.TextField txtOptionC;
    private java.awt.TextField txtOptionD;
    String filenameQuest ;
    String filenameAns ;
    // End of variables declaration//GEN-END:variables

    
    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            if(command.equals("back")){
                btnBack.getParent().setVisible(false);
                new PhysicsModifyQuestion().setVisible(true);
            }
            else{
                if(Subject.Subject.equals("phy")){
                    filenameQuest = ("PhysicsQuestions.txt");
                    filenameAns = ("PhysicsAnswers.txt");
                }
                if(Subject.Subject.equals("chem")){
                    filenameQuest = ("ChemistryQuestions.txt");
                    filenameAns = ("ChemAnswers.txt");
                }
                try{
                    //storing questions in file
                    FileReader fileReaderQuest = new FileReader(filenameQuest);
                    BufferedReader bufferedReaderQuest = new BufferedReader(fileReaderQuest);
                    FileReader fileReaderAns = new FileReader(filenameAns);
                    BufferedReader bufferedReaderAns = new BufferedReader(fileReaderAns);
                    
                    int answerNumber = questionNumber;
                    String strQuest;
                    String strAns;
                    String strQuestionNumber = String.valueOf(questionNumber);
                    String newQuestion = strQuestionNumber + "." + txtQuestion.getText().toString() + " (" + txtOptionA.getText().toString()+ "," + txtOptionB.getText().toString() + "," + txtOptionC.getText().toString()+ "," + txtOptionD.getText().toString() + ")" + " -MCQ ";
                    String newAnswer = strQuestionNumber + "." + txtAnswer.getText().toString();
                    ArrayList<String> StringOfQuestions = new ArrayList<String>();
                    ArrayList<String> StringOfAnswers = new ArrayList<String>();
                    while((strQuest = bufferedReaderQuest.readLine())!=null){
                        StringOfQuestions.add(strQuest);
                    }
                    while((strAns=bufferedReaderAns.readLine())!=null){
                        StringOfAnswers.add(strAns);
                    }
                    FileWriter fileWriterQuest = new FileWriter(filenameQuest,false);
                    BufferedWriter bufferedWriterQuest = new BufferedWriter(fileWriterQuest);
                    FileWriter fileWriterAns = new FileWriter(filenameAns,false);
                    BufferedWriter bufferedWriterAns = new BufferedWriter(fileWriterAns);
                    try{
                       StringOfQuestions.set((questionNumber-1),newQuestion);
                        StringOfAnswers.set((questionNumber-1),newAnswer);
                    for(int i=0;i<StringOfQuestions.size();i++){
                        bufferedWriterQuest.write(StringOfQuestions.get(i));
                        bufferedWriterQuest.newLine();
                        bufferedWriterAns.write(StringOfAnswers.get(i));
                        bufferedWriterAns.newLine();
                    }
                     bufferedWriterQuest.close();
                     bufferedWriterAns.close();
                    }
                    catch(Exception ex){
                        System.out.println("Questions list is empty");
                    }
                    

                }
                catch(IOException ex){
                    System.out.println("error");
                }
            }

        }

    }
}
