/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */

import java.awt.*;
import java.awt.event.*;
import java.io.*;

public class PhysicsInsertTrueFalseQuest extends java.awt.Frame {

    /**
     * Creates new form InsertPhyTrueFalseQuest
     */
    public PhysicsInsertTrueFalseQuest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatement = new java.awt.Label();
        lblAction = new java.awt.Label();
        lblTrueFalse = new java.awt.Label();
        txtStatement = new java.awt.TextField();
        btnInsert = new java.awt.Button();
        btnBack = new java.awt.Button();
        txtTrueFalse = new java.awt.TextField();

        setName("Insert Physics True or False Question"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setLayout(new FlowLayout());
        setSize(1000,1000);

        lblStatement.setText("Statement");
        add(lblStatement);
        lblStatement.setBounds(37, 77, 60, 20);

        lblAction.setText("Insert True or False Question");
        add(lblAction);
        lblAction.setBounds(105, 38, 164, 20);

        add(txtStatement);
        txtStatement.setBounds(124, 77, 223, 20);

        lblTrueFalse.setText("True or False");
        add(lblTrueFalse);
        lblTrueFalse.setBounds(37, 124, 77, 20);

        btnInsert.setLabel("Insert Question");
        btnInsert.setActionCommand("insert");
        add(btnInsert);
        btnInsert.setBounds(105, 209, 100, 24);
        btnInsert.addActionListener(new ButtonClickListener());

        btnBack.setLabel("Back");
        btnBack.addActionListener(new ButtonClickListener());
         add(btnBack);
        btnBack.setBounds(304, 243, 43, 24);
        btnBack.setActionCommand("back");


        txtTrueFalse.setText("Enter True or False");
        add(txtTrueFalse);
        txtTrueFalse.setBounds(124, 124, 123, 20);

        

       setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsInsertTrueFalseQuest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private java.awt.Button btnInsert;
    private java.awt.Label lblAction;
    private java.awt.Label lblStatement;
    private java.awt.Label lblTrueFalse;
    private java.awt.TextField txtStatement;
    private java.awt.TextField txtTrueFalse;

    String filenameQuest ;
    String filenameAns;
    // End of variables declaration//GEN-END:variables

    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            if(command.equals("back")){
                btnBack.getParent().setVisible(false);
                new PhysicsInsertQuestion().setVisible(true);
            }
            else{
                if(Subject.Subject.equals("phy")){
                    filenameQuest = ("PhysicsQuestions.txt");
                    filenameAns = ("PhysicsAnswers.txt");
                }
                if(Subject.Subject.equals("chem")){
                    filenameQuest = ("ChemistryQuestions.txt");
                    filenameAns = ("ChemAnswers.txt");
                }
                try{
                    FileReader fileReaderQuest = new FileReader(filenameQuest);
                    BufferedReader bufferedReaderQuest = new BufferedReader(fileReaderQuest);
                    FileWriter fileWriterQuest = new FileWriter(filenameQuest,true);
                    BufferedWriter bufferedWriterQuest = new BufferedWriter(fileWriterQuest);
                    int questionNumber = 1;
                    String lineQuest;
                    while((lineQuest = bufferedReaderQuest.readLine()) !=null){
                        questionNumber++;
                    }
                    //bufferedWriter.write(questionNumber + "." +);
                    bufferedWriterQuest.write((questionNumber) + "." + txtStatement.getText().toString() + " -True/False");
                    bufferedWriterQuest.newLine();
                    bufferedWriterQuest.close();

                    //Inserting answer into File
                    FileReader fileReaderAns = new FileReader(filenameAns);
                    BufferedReader bufferedReaderAns= new BufferedReader(fileReaderAns);
                    FileWriter fileWriterAns = new FileWriter(filenameAns,true);
                    BufferedWriter bufferedWriterAns = new BufferedWriter(fileWriterAns);
                    int answerNumber = 1;
                    String lineAns;
                    while((lineAns = bufferedReaderAns.readLine()) !=null){
                        answerNumber++;
                    }
                    //bufferedWriter.write(questionNumber + "." +);
                    bufferedWriterAns.write((answerNumber) + "." + txtTrueFalse.getText().toString());
                    bufferedWriterAns.newLine();
                    bufferedWriterAns.close();






                }
                catch(IOException ex){
                    System.out.println("error");
                }
            }

        }
    }
}

