/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhiram
 */

import java.awt.*;
import java.awt.event.*;

public class PhysicsHomePage extends java.awt.Frame {

static String subject;
    /**
     * Creates new form PhysicsHomePage
     */
    public PhysicsHomePage(String subject) {
        initComponents();
        this.subject = subject;
    }

    public PhysicsHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsert = new java.awt.Button();
        btnModify = new java.awt.Button();
        btnDelete = new java.awt.Button();
        btnGenerate = new java.awt.Button();
        btnBack = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setLayout(new FlowLayout());
        setSize(1000,1000);

        btnInsert.setLabel("Insert Question");
        btnInsert.setActionCommand("ins");
        add(btnInsert);
        btnInsert.setBounds(131, 49, 100, 24);
        btnInsert.addActionListener(new ButtonClickListener());

        btnModify.setLabel("Modify Question");
        btnModify.setActionCommand("mod");
        add(btnModify);
        btnModify.setBounds(131, 110, 103, 24);
        btnModify.addActionListener(new ButtonClickListener());

        btnDelete.setLabel("Delete Question");
        btnDelete.setActionCommand("del");
        add(btnDelete);
        btnDelete.setBounds(131, 166, 105, 24);
        btnDelete.addActionListener(new ButtonClickListener());


        btnGenerate.setLabel("Generate Test");
        btnGenerate.addActionListener(new ButtonClickListener());
        btnGenerate.setBounds(131, 236, 94, 24);
        add(btnGenerate);
        btnGenerate.setActionCommand("gen");

        btnBack.setLabel("Back");
        btnBack.setActionCommand("back");
        add(btnBack);
        btnBack.setBounds(323, 258, 43, 24);
        btnBack.addActionListener(new ButtonClickListener());

        
        setLayout(null);

        
        
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsHomePage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private java.awt.Button btnDelete;
    private java.awt.Button btnGenerate;
    private java.awt.Button btnInsert;
    private java.awt.Button btnModify;
    // End of variables declaration//GEN-END:variables

    public class ButtonClickListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
          String command = e.getActionCommand();
          if(command.equals("ins")){
            btnInsert.getParent().setVisible(false);
            new PhysicsInsertQuestion().setVisible(true);
          }
          if(command.equals("mod")){
            btnModify.getParent().setVisible(false);
            new PhysicsModifyQuestion().setVisible(true);
          }
          if(command.equals("del")){
            btnDelete.getParent().setVisible(false);
            new PhysicsDeleteQuestion().setVisible(true);
          }
          if(command.equals("back")){
            btnBack.getParent().setVisible(false);
            new Subject().setVisible(true);
          }
          if(command.equals("gen")){
            btnGenerate.getParent().setVisible(false);
            new GenerateTest().setVisible(true);
          }
        }
    }
}
